
export const API_ERROR ={
    VALIDATION_ERROR: "VALIDATION_ERROR",
    INVALID_CREDENTIALS: "INVALID_CREDENTIALS",

    EXPIRED_TOKEN: "EXPIRED_TOKEN",
    INVALID_TOKEN: "INVALID_TOKEN",

    FORBIDDEN: "FORBIDDEN",

    USER_NOT_FOUND: "USER_NOT_FOUND",
    USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS"
}
